{
 "title": "cAdvisor Docker Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_network_receive_bytes_total{name!=\"\"}[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total[5m]))",
     "legendFormat": "RX - {{ name }}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{name=~\".+\"}[5m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{name=~\".+\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}