version: '3'
services:
  #
  # Client
  #
  client:
    image: von-network-base
    command: ./scripts/start_client.sh
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - RUST_LOG=${RUST_LOG}
    networks:
      - von
    volumes:
      - client-data:/home/indy/.indy_client
      - ./tmp:/tmp

  #
  # Webserver
  #
  webserver:
    image: von-network-base
    command: bash -c 'sleep 10 && ./scripts/start_webserver.sh'
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
      - GENESIS_URL=${GENESIS_URL}
      - LEDGER_SEED=${LEDGER_SEED}
      - LEDGER_CACHE_PATH=${LEDGER_CACHE_PATH}
      - MAX_FETCH=${MAX_FETCH:-50000}
      - RESYNC_TIME=${RESYNC_TIME:-120}
      - POOL_CONNECTION_ATTEMPTS=${POOL_CONNECTION_ATTEMPTS:-5}
      - POOL_CONNECTION_DELAY=${POOL_CONNECTION_DELAY:-10}
      - REGISTER_NEW_DIDS=${REGISTER_NEW_DIDS:-True}
      - LEDGER_INSTANCE_NAME=${LEDGER_INSTANCE_NAME:-localhost}
      - WEB_ANALYTICS_SCRIPT=${WEB_ANALYTICS_SCRIPT}
      - INFO_SITE_TEXT=${INFO_SITE_TEXT}
      - INFO_SITE_URL=${INFO_SITE_URL}
      - INDY_SCAN_URL=${INDY_SCAN_URL}
      - INDY_SCAN_TEXT=${INDY_SCAN_TEXT}
    networks:
      - von
    ports:
      - ${WEB_SERVER_HOST_PORT:-9000}:8000
    volumes:
      - ./config:/home/indy/config
      - ./server:/home/indy/server
      - webserver-cli:/home/indy/.indy-cli
      - webserver-ledger:/home/indy/ledger

  #
  # Synchronization test
  #
  synctest:
    image: von-network-base
    command: ./scripts/start_synctest.sh
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
    networks:
      - von
    ports:
      - ${WEB_SERVER_HOST_PORT:-9000}:8000
    volumes:
      - ./config:/home/indy/config
      - ./server:/home/indy/server
      - webserver-cli:/home/indy/.indy-cli
      - webserver-ledger:/home/indy/ledger

  #
  # Nodes
  #
  nodes:
    image: von-network-base
    command: ./scripts/start_nodes.sh
    networks:
      - von
    ports:
      - 9701:9701
      - 9702:9702
      - 9703:9703
      - 9704:9704
      - 9705:9705
      - 9706:9706
      - 9707:9707
      - 9708:9708
      - 9709:9709
      - 9710:9710
      - 9711:9711
      - 9712:9712
      - 9713:9713
      - 9714:9714
      - 9715:9715
      - 9716:9716
      - 9717:9717
      - 9718:9718
      - 9719:9719
      - 9720:9720
      - 9721:9721
      - 9722:9722
      - 9723:9723
      - 9724:9724
      - 9725:9725
      - 9726:9726
      - 9727:9727
      - 9728:9728
      - 9729:9729
      - 9730:9730
      - 9731:9731
      - 9732:9732

    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - nodes-data:/home/indy/ledger

  node1:
    image: von-network-base
    command: ./scripts/start_node.sh 1
    networks:
      - von
    ports:
      - 9701:9701
      - 9702:9702
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node1-data:/home/indy/ledger

  node2:
    image: von-network-base
    command: ./scripts/start_node.sh 2
    networks:
      - von
    ports:
      - 9703:9703
      - 9704:9704
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node2-data:/home/indy/ledger

  node3:
    image: von-network-base
    command: ./scripts/start_node.sh 3
    networks:
      - von
    ports:
      - 9705:9705
      - 9706:9706
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node3-data:/home/indy/ledger

  node4:
    image: von-network-base
    command: ./scripts/start_node.sh 4
    networks:
      - von
    ports:
      - 9707:9707
      - 9708:9708
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node4-data:/home/indy/ledger

  node5:
      image: von-network-base
      command: 'bash -c ''./scripts/start_node.sh 5'''
      networks:
        - von
      ports:
        - 9709:9709
        - 9710:9710
      environment:
        - IP=${IP}
        - IPS=${IPS}
        - DOCKERHOST=${DOCKERHOST}
        - LOG_LEVEL=${LOG_LEVEL}
        - RUST_LOG=${RUST_LOG}
      volumes:
        - node5-data:/home/indy/ledger

  node6:
      image: von-network-base
      command: 'bash -c ''./scripts/start_node.sh 6'''
      networks:
        - von
      ports:
        - 9711:9711
        - 9712:9712
      environment:
        - IP=${IP}
        - IPS=${IPS}
        - DOCKERHOST=${DOCKERHOST}
        - LOG_LEVEL=${LOG_LEVEL}
        - RUST_LOG=${RUST_LOG}
      volumes:
        - node6-data:/home/indy/ledger

  node7:
      image: von-network-base
      command: 'bash -c ''./scripts/start_node.sh 7'''
      networks:
        - von
      ports:
        - 9713:9713
        - 9714:9714
      environment:
        - IP=${IP}
        - IPS=${IPS}
        - DOCKERHOST=${DOCKERHOST}
        - LOG_LEVEL=${LOG_LEVEL}
        - RUST_LOG=${RUST_LOG}
      volumes:
        - node7-data:/home/indy/ledger

  node8:
      image: von-network-base
      command: 'bash -c ''./scripts/start_node.sh 8'''
      networks:
        - von
      ports:
        - 9715:9715
        - 9716:9716
      environment:
        - IP=${IP}
        - IPS=${IPS}
        - DOCKERHOST=${DOCKERHOST}
        - LOG_LEVEL=${LOG_LEVEL}
        - RUST_LOG=${RUST_LOG}
      volumes:
        - node8-data:/home/indy/ledger

  node9:
      image: von-network-base
      command: 'bash -c ''./scripts/start_node.sh 9'''
      networks:
        - von
      ports:
        - 9717:9717
        - 9718:9718
      environment:
        - IP=${IP}
        - IPS=${IPS}
        - DOCKERHOST=${DOCKERHOST}
        - LOG_LEVEL=${LOG_LEVEL}
        - RUST_LOG=${RUST_LOG}
      volumes:
        - node9-data:/home/indy/ledger

  node10:
      image: von-network-base
      command: 'bash -c ''./scripts/start_node.sh 10'''
      networks:
        - von
      ports:
        - 9719:9719
        - 9720:9720
      environment:
        - IP=${IP}
        - IPS=${IPS}
        - DOCKERHOST=${DOCKERHOST}
        - LOG_LEVEL=${LOG_LEVEL}
        - RUST_LOG=${RUST_LOG}
      volumes:
        - node10-data:/home/indy/ledger

  node11:
      image: von-network-base
      command: 'bash -c ''./scripts/start_node.sh 11'''
      networks:
        - von
      ports:
        - 9721:9721
        - 9722:9722
      environment:
        - IP=${IP}
        - IPS=${IPS}
        - DOCKERHOST=${DOCKERHOST}
        - LOG_LEVEL=${LOG_LEVEL}
        - RUST_LOG=${RUST_LOG}
      volumes:
        - node11-data:/home/indy/ledger

  node12:
      image: von-network-base
      command: 'bash -c ''./scripts/start_node.sh 12'''
      networks:
        - von
      ports:
        - 9723:9723
        - 9724:9724
      environment:
        - IP=${IP}
        - IPS=${IPS}
        - DOCKERHOST=${DOCKERHOST}
        - LOG_LEVEL=${LOG_LEVEL}
        - RUST_LOG=${RUST_LOG}
      volumes:
        - node12-data:/home/indy/ledger

  node13:
      image: von-network-base
      command: 'bash -c ''./scripts/start_node.sh 13'''
      networks:
        - von
      ports:
        - 9725:9725
        - 9726:9726
      environment:
        - IP=${IP}
        - IPS=${IPS}
        - DOCKERHOST=${DOCKERHOST}
        - LOG_LEVEL=${LOG_LEVEL}
        - RUST_LOG=${RUST_LOG}
      volumes:
        - node13-data:/home/indy/ledger

  node14:
      image: von-network-base
      command: 'bash -c ''./scripts/start_node.sh 14'''
      networks:
        - von
      ports:
        - 9727:9727
        - 9728:9728
      environment:
        - IP=${IP}
        - IPS=${IPS}
        - DOCKERHOST=${DOCKERHOST}
        - LOG_LEVEL=${LOG_LEVEL}
        - RUST_LOG=${RUST_LOG}
      volumes:
        - node14-data:/home/indy/ledger

  node15:
      image: von-network-base
      command: 'bash -c ''./scripts/start_node.sh 15'''
      networks:
        - von
      ports:
        - 9729:9729
        - 9730:9730
      environment:
        - IP=${IP}
        - IPS=${IPS}
        - DOCKERHOST=${DOCKERHOST}
        - LOG_LEVEL=${LOG_LEVEL}
        - RUST_LOG=${RUST_LOG}
      volumes:
        - node15-data:/home/indy/ledger

  node16:
      image: von-network-base
      command: 'bash -c ''./scripts/start_node.sh 16'''
      networks:
        - von
      ports:
        - 9731:9731
        - 9732:9732
      environment:
        - IP=${IP}
        - IPS=${IPS}
        - DOCKERHOST=${DOCKERHOST}
        - LOG_LEVEL=${LOG_LEVEL}
        - RUST_LOG=${RUST_LOG}
      volumes:
        - node16-data:/home/indy/ledger


networks:
  von:

volumes:
  client-data:
  webserver-cli:
  webserver-ledger:
  node1-data:
  node2-data:
  node3-data:
  node4-data:
  node5-data:
  node6-data:
  node7-data:
  node8-data:
  node9-data:
  node10-data:
  node11-data:
  node12-data:
  node13-data:
  node14-data:
  node15-data:
  node16-data:
  nodes-data:
